ShoppingWebsiteMVC/Models/Product.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ShoppingWebsiteMVC.Models
{
    public class Product
    {
        [Required]
        [Display(Name ="ProductCode")]
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ProductId { get; set; }
        [Required]
        [Display(Name ="ProductName")]
        public string ProductName { get; set; }

        [Required]
        [Display(Name ="Brand")]
        public string BrandName { get; set; }
        [Required]
        [Display(Name ="Cost")]
        public double Price { get; set; }
        [Required]
        [Display(Name ="Units")]
        public int Units { get; set; }
        [Display(Name ="Discount")]
        public double Discount { get; set; }
        public int SubCategoryId { get; set; }
        public int SupplierId { get; set; }
        public double GetAmount(double price,double discount,int units)
        {
            double totamount = (price - (discount / 100) * price) * units;
            return totamount;
        }

        public virtual ICollection<Cart> Carts { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<Feedback> Feedbacks { get; set; }
        public virtual SubCategory SubCategory { get; set; }
        public virtual Supplier Supplier { get; set; }


    }
    
}

ShoppingWebsiteMVC/Models/SubCategory.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace ShoppingWebsiteMVC.Models
{
    public class SubCategory
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int SubCategoryId { get; set; }
        public string Name { get; set; }
        public int CategoryId { get; set; }


        public virtual ICollection<Product> Products { get; set; }
        public virtual Category Category { get; set; }
    }
}

ShoppingWebsiteMVC/Controllers/PayController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ShoppingWebsiteMVC.Models;

namespace ShoppingWebsiteMVC.Controllers
{
    public class PayController : Controller
    {
        private DbShopContext db = new DbShopContext();

        // GET: Pay
        public ActionResult Index()
        {
            return View(db.Payments.ToList());
        }

        // GET: Pay/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Payments payments = db.Payments.Find(id);
            if (payments == null)
            {
                return HttpNotFound();
            }
            return View(payments);
        }

        // GET: Pay/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Pay/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Card_Number,Espiry_Date,Email,VCC")] Payments payments)
        {
            if (ModelState.IsValid)
            {


                db.Payments.Add(payments);
                db.SaveChanges();
                return RedirectToAction("ConfirmAllOrder", "Product");
            }

            return View(payments);
        }

        // GET: Pay/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Payments payments = db.Payments.Find(id);
            if (payments == null)
            {
                return HttpNotFound();
            }
            return View(payments);
        }

        // POST: Pay/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Card_Number,Espiry_Date,Email,VCC")] Payments payments)
        {
            if (ModelState.IsValid)
            {
                db.Entry(payments).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(payments);
        }

        // GET: Pay/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Payments payments = db.Payments.Find(id);
            if (payments == null)
            {
                return HttpNotFound();
            }
            return View(payments);
        }

        // POST: Pay/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Payments payments = db.Payments.Find(id);
            db.Payments.Remove(payments);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ShoppingWebsiteMVC/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ShoppingWebsiteMVC.Models;
using System.Data.Entity;
using System.Web.DynamicData;
using System.Xml.Linq;

namespace ShoppingWebsiteMVC.Controllers
{
    public class ProductController : Controller
    {
        Models.DbShopContext db = new Models.DbShopContext();
        // GET : Products by Category
        [HttpGet]
        public ActionResult Index(string id)
        {
            string category = id;
            if(category==null)
            {
                return View(db.Categories.Where(p => p.Name != null).ToList());
            }
            else
            {
                if (category == "All")
                {
                    // return the View named Products with all products list
                    return View("Products",db.Products.ToList());
                }
                else
                {
                    var subcategory = db.SubCategories.Where(p => p.Category.Name.Equals(category)).ToList();
                        
                    if (subcategory != null)
                    {
                        // return the View named Products with the required category lists 
                        return View("SubCategory",subcategory);
                    }
                    else
                    {
                        ViewBag.Error = "Invalid Category";
                    }
                    // return the View named Products without any data 
                    return View("Products");
                }
            }
        }
        //View all the subcategories of a selected category
        public ActionResult SubCategory(string id)
        {
            string subcategory = id;
            if (subcategory != null)
            {
                var products = db.Products.Where(pro => pro.SubCategory.Name.Equals(subcategory)).ToList();
                if (products != null)
                {
                    return View("Products",products);
                }
                else
                {
                    ViewBag.Error = "Invalid Selection";
                }
                return View("Products");
            }
            else
            {
                return RedirectToAction("Index");
            }
        }
        
        //Get Search product by productname
        public ActionResult Search(string id)
        {
            string ProductName = id;
            var list = new List<Product>();
            if(String.IsNullOrEmpty(ProductName))
            {
                list = db.Products.ToList();
            }
            else
            {
                list = db.Products.Where(p => p.ProductName.ToLower().Equals(ProductName.ToLower())).ToList();
                if (list.Count == 0)
                {
                    list = db.Products.Where(p => p.SubCategory.Category.Name.ToLower().Equals(ProductName.ToLower())).ToList();
                    if (list.Count == 0)
                    {
                        list = db.Products.Where(p => p.BrandName.ToLower().Equals(ProductName.ToLower())).ToList();
                    }
                }
            }
            ViewBag.Title= "Search Result";
            return View("Products",list);
        }
        //Get details of a product 
        public ActionResult ProductView(int? id)
        {
            if (id != null)
            {
                int ProductId = (int)id;
                

                Product product = db.Products.Find(ProductId);
                if (product == null)
                {
                    
                    return HttpNotFound();
                }
                
                if (TempData["status"] != null && TempData["message"] != null)
                {
                    ViewBag.status = TempData["status"].ToString();
                    ViewBag.message = TempData["message"].ToString();
                    TempData["status"] = null;
                    TempData["message"] = null;

                }
                return View(product);
            }
            else
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
        }
     
        [Authorize]
        [HttpPost]
        public ActionResult AddtoCart(string itemno,int? ProductId)
        {
            if(Session["UserId"]!=null && Session["Role"].ToString() == "User")
            {
                string UserId =Session["UserId"].ToString();
                int noofunits = int.Parse(itemno);
                if (ProductId==null)
                {
                    ViewBag.Error = "Empty";
                }
                else
                {
                    var p = db.Products.Find(ProductId);

                    if (noofunits > p.Units)
                    {
                        TempData["status"] = "danger";
                        TempData["message"] = "No stock available";
                        return ProductView(id: ProductId);
                    }
                    else
                    {
                        if (db.Carts.Where(car => car.ProductId==ProductId && car.UserId.Equals(UserId)).FirstOrDefault() != null)
                        {

                            Cart cart = db.Carts.Where(car => car.ProductId==ProductId && car.UserId.Equals(UserId)).FirstOrDefault();
                            cart.NoofProduct= cart.NoofProduct+noofunits;
                            db.Entry(cart).State = EntityState.Modified;
                            db.SaveChanges();
                        }
                        else
                        {
                            Cart cart = new Cart();
                            cart.UserId = Session["UserId"].ToString();
                            cart.ProductId = p.ProductId;
                            cart.NoofProduct = noofunits;
                            cart.Amount = p.GetAmount(p.Price, p.Discount, noofunits);
                            db.Carts.Add(cart);
                            db.SaveChanges();
                        }
                    }
                }
                return RedirectToAction("Cart","User");
            }
            else
            {
                return Redirect("/User/Index?ReturnUrl=/Product/ProductView/"+ProductId+"");
            }
        }
        [Authorize]
        public ActionResult BuyNow(string UserId,string ProductId)
        {

            ViewBag.UserId = UserId;
            ViewBag.ProductId = ProductId;
            var user=db.Users.Where(u => u.UserId.Equals(UserId)).FirstOrDefault();
            return View(user);
        }
        [Authorize]
        public ActionResult ConfirmOrder(string UserId, int? ProductId)
        {
            if (ProductId==null)
            {
                ViewBag.Error = "Empty";
            }
            else
            {
                var c = db.Carts.Where(cart => cart.UserId.Equals(UserId)&&cart.ProductId==ProductId).FirstOrDefault();

                var p = db.Products.Where(product => product.ProductId==ProductId).FirstOrDefault();
                if (c.NoofProduct >p.Units )
                {
                    ViewBag.Error = "No stock available";
                }
                else
                {
                    Order Trx = new Order();
                    Transaction newbill = new Transaction();
                    var t=db.Orders.Select(tn => tn.TId).DefaultIfEmpty(0).Max()+1;
                    newbill.TId = t;
                    newbill.Amount = c.Amount;
                    db.Transactions.Add(newbill);
                    db.SaveChanges();
                   
                    Trx.TId = t;
                    Trx.UserId = c.UserId;
                    Trx.ProductId = c.ProductId;
                    Trx.NoofProduct = c.NoofProduct;
                    Trx.Amount = c.Amount;
                    Trx.TDate = DateTime.Now;
                    db.Orders.Add(Trx);
                    db.SaveChanges();
                    p.Units = p.Units - c.NoofProduct;
                    db.Entry(p).State = EntityState.Modified;
                    db.SaveChanges();
                    db.Carts.Remove(c);
                    db.SaveChanges(); 
                }
            }
            return RedirectToAction("MyOrders","User");
        }
        [Authorize]
        public ActionResult BuyAll()
        {
            double sum = 0;
            string UserId = Session["UserId"].ToString();
            var cart = db.Carts.Where(c => c.UserId.Equals(UserId)).ToList();
            foreach(Cart c in cart)
            {
                sum = sum + c.Amount;
            }
            ViewBag.TotalSum = sum;
            var user = db.Users.Where(u => u.UserId.Equals(UserId)).FirstOrDefault();
            ViewBag.Address = user.Address+"\n"+user.City+"\n"+user.Country;
            ViewBag.Name = user.Firstname + " " + user.Lastname;
            return View(cart);
        }
        [Authorize]
        public ActionResult ConfirmAllOrder()
        {
            string UserId = Session["UserId"].ToString();
            var cart = db.Carts.Where(c => c.UserId.Equals(UserId)).ToList();
            var t = db.Transactions.Select(tn => tn.TId).DefaultIfEmpty(0).Max()+1;
            Transaction newbill = new Transaction();
            newbill.TId = t;
            db.Transactions.Add(newbill);
            db.SaveChanges();
            double sum = 0;
           
            for (int i=0;i<cart.Count;i++)
            {
                Order Trx = new Order();
                Trx.TId = t;
                Trx.UserId = cart[i].UserId;
                var c = cart[i].ProductId;
                Trx.ProductId = c;
                Trx.NoofProduct = cart[i].NoofProduct;
                Trx.Amount = cart[i].Amount;
                sum = sum + Trx.Amount;
                Trx.TDate = DateTime.Now;
                db.Orders.Add(Trx);

ShoppingWebsiteMVC/Views/Product/BuyAll.cshtml
@model IEnumerable<ShoppingWebsiteMVC.Models.Cart>

@{
    ViewBag.Title = "Confirm Order";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    .gt {
        color: white;
    }
    .UP {
        margin-top: 20px;
        margin-bottom: 20px;
        color: blue !important;
    }
</style>
<div class="UP">
    @Html.ActionLink("Update Address", "Edit", "User", null, new { @class = "btn btn-success col-md-3 col-6" })
</div>

<h2 class="gt">Pay Your Order</h2>
<h4 class="gt">Confirm Payment</h4>
<p class="gt">
    ThankYou @ViewBag.Name, for shopping with us

    <br />
<p class="gt">
<p class="gt">Your Order will be delevered to - </p>
<br />
<blockquote class="gt"> @ViewBag.Address</blockquote>
</p>

<div class="alert-info" class="gt">Complete your payment by clicking paynow</div>

<table class="table">
    <tr>
        <th colspan="3" class="gt">
            Review Your orders
        </th>

    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td class="gt">
                @Html.DisplayFor(modelItem => item.Products.ProductName)
            </td>
            <td class="gt">
                @Html.DisplayFor(modelItem => item.NoofProduct)
            </td>
            <td class="gt">
                @Html.DisplayFor(modelItem => item.Amount)
            </td>

        </tr>
    }
    <p class="gt"> Total Amount to be Paid <b>R @ViewBag.TotalSum</b></p>
</table>

@Html.ActionLink("Pay Now", "Create", "Pay", null, new { @class = "btn btn-success col-4" })
@*@Html.ActionLink("Pay Now", "ConfirmAllOrder", "Product", null, new { @class = "btn btn-success col-4" })*@

ShoppingWebsiteMVC/Views/Product/BuyNow.cshtml
@model ShoppingWebsiteMVC.Models.User

@{
    ViewBag.Title = "BuyNow";
}
<style>
    .LL{
        color:black;
    }
</style>
<h2  class="LL">Pay Your Order</h2>

<div>
    <h4  class="LL">Confirm Payment</h4>
    <hr />

    <div class="LL">Thankyou </div>
    <div class="LL"> @Html.DisplayFor(model => model.Firstname) @Html.DisplayFor(model => model.Lastname), for shopping with us</div>
    <p class="LL">Your order will be delivered to: </p>
    <blockquote>
        <div class="LL">@Html.DisplayFor(model => model.Address)</div> 
        <br />
        <div class="LL">@Html.DisplayFor(model => model.City)</div> 
        <br />
        <div  class="LL"> @Html.DisplayFor(model => model.Country)</div> 
    </blockquote>
    <div class="alert-info"class="LL">Complete your payment by clicking paynow</div>
    @*<div>
        @Html.ActionLink("Pay Now", "ConfirmOrder", new { UserId = ViewBag.UserId, ProductId = ViewBag.ProductId }, new { @class = "mt-2 col-4 btn btn-success" })
    </div>*@
<div>
    @Html.ActionLink("Pay Now", "Create", "Pay", null, new { @class = "btn btn-success col-4" })

</div>
</div>
<p class="mt-2">
     @Html.ActionLink("Back to Cart", "Cart","User",null, new { @class = "btn btn-info btn-sm" })
</p>

ShoppingWebsiteMVC/Views/Product/Index.cshtml
@model IEnumerable<ShoppingWebsiteMVC.Models.Category>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.home = "active";
}
<style>
    .Schools {
        align-items: end;
        text-align-last: end;
        margin-top: 15px;
        margin-bottom: 15px;
        border:double;
        border-block:dashed;
        border-color:red;
        width:80px;
        padding-right:50px;
        background-color:red;
        text-decoration-color:blue;
        background:transparent;
    }

    .hrr {
        background-color: rgb(43, 155, 207);
        height: 1px;
        width: 700px;
    }
    .Vcc {
        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        color: rgb(90, 156, 161);
        margin-top:20px;
        margin-bottom:20px;
        text-align:center;
        


        
    }
        .Vcc:hover {
            opacity: 1;
            color: rgb(207, 120, 43);
            transition-duration: 0.7s;
            cursor: pointer;
            font-size: 25px;
        }
    .please {
        color: rgb(43, 207, 199);
        margin-bottom: 20px;
    }
    body {
        background-image: url(../images/background.jpg);
        background-size: cover;
        background-repeat: no-repeat;
        background-position: center;
    }
    /*.Schools {
        background-color: blue;
    }*/
   /* body{
        background-color:grey;
    }*/
</style>
<hr class="hrr" />
<h3 class="Vcc">
   Welcome to VCC Branding clothings
</h3>
<h2 class="please">
    Please select University 
</h2>
<div class="m-3" class="Schools">
    @foreach (var item in Model)
    {
        @Html.ActionLink(item.Name, "Index", new { id = item.Name }, new { @class = "list-group-item list-group-item-action" })
    }


</div>
<div >
    @Html.ActionLink("All Products", "Index", new { id = "All" }, new { @class = "list-group-item list-group-item-action" })
</div>

ShoppingWebsiteMVC/Views/Product/Products.cshtml
@model IEnumerable<ShoppingWebsiteMVC.Models.Product>

@{
    ViewBag.Title = "Products";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    .container {
        max-width: 100%;
        padding: 0;
    }
</style>

@if (!string.IsNullOrEmpty(ViewBag.Error))
{
    <div class="alert-danger">@ViewBag.Error</div>
}
else
{
    if (Model.ToList().Count==0)
    {
        <div class="alert-danger p-3 pl-5 m-3">No products found <i class="fa fa-close"></i>. Search for another product!</div>
    }
    else
    {
    <div class="row p-0 m-0 w-100 mb-2" style="background-image:url('../../Images/banner.png');background-size:contain;border-bottom:solid">
        <h4 class="p-3 text-black-50 alert-heading">Select from a wide range of products</h4>
    </div>
<div class="p-2 m-3">
    <div class="row">
                @foreach (var item in Model)
                {
                    <div class="col-sm-3 mb-2" >
                        <div class="card p-1" style="height:380px" id="productcard">
                            <div class="card-img text-center">
                                @{ var img = item.ProductId + ".jpg";}
                                <img src="~/Images/@img" height="100" />
                            </div>
                            <div class="card-header text-center">
                                @Html.DisplayFor(modelItem => item.ProductName)
                            </div>
                            <div class="font-weight-bold text-center" style="font-size:large">
                                @Html.DisplayFor(modelItem => item.BrandName)
                            </div>
                            <div class="card-body text-center">
                                R @Html.DisplayFor(modelItem => item.Price) <br />
                                <span class="alert-info">@Html.DisplayFor(modelItem => item.Discount)% off</span>
                            </div>
                            <div class="card-footer text-center">
                                @Html.ActionLink("Details", "ProductView", new { id = item.ProductId }, new { @class = "btn btn-info stretched-link" })
                            </div>
                        </div>
                    </div>
                }
    </div>
</div>
}
    }

ShoppingWebsiteMVC/Views/Product/SubCategory.cshtml
@model IEnumerable<ShoppingWebsiteMVC.Models.SubCategory>

@{
    ViewBag.Title = "SubCategory";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (!string.IsNullOrEmpty(ViewBag.Error))
{
    <div class="alert-danger p-3 pl-5 m-3">@ViewBag.Error</div>
}
else
{
    if (Model.ToList().Count == 0)
    {
        <div class="alert-danger p-3 pl-5 m-3">No products found in this category<i class="fa fa-close"></i>. Search Products or select another category</div>
    }
    else
    {
        <div class="m-3">
        @foreach (var item in Model)
        {
                @Html.ActionLink(item.Name, "SubCategory", "Product", new { id = item.Name }, new { @class = "list-group-item list-group-item-action" })
        }
        @Html.ActionLink("View All Products", "Index", "Product", new { id = "All" }, new { @class = "list-group-item list-group-item-action" })
        </div>
    }
}